### ISSUE TITLE
Change branding to Taboggan

### ISSUE THREAD

**Issue by jmcmurry** [INCATools/table-editor#1]
Feedback for Taboggan as the branding for this tool has been so far positive. It would be great to rename the repo accordingly. I can work on some logo ideas.

**Comment by jmcmurry** [comment]
downside is jeepers it is hard to spell

**Comment by cmungall** [comment]
+1 to rename

**Comment by jmcmurry** [comment]
Going to close this as it hasn't had the broadest appeal
