### ISSUE TITLE
Importing *.tab phenotype annotation files doesnt work

### ISSUE THREAD

**Issue by pnrobinson** [INCATools/table-editor#15]
Although this function worked during our call yesterday, I have not been able to get it to work on my laptop or desktop (both Ubuntu linux). Neither drag and drop nor using the Xsl file chooser leads to any response by the GUI (i.e., nothing happens).

**Comment by DoctorBud** [comment]
Please verify this is still a problem and close this ticket if not, @pnrobinson

**Comment by pnrobinson** [comment]
Current status: working fine!
